import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

const taskActionsPath = join(process.cwd(), 'src/components/chat/ComposerTaskActions.vue');
const taskAdvisorPath = join(process.cwd(), 'src/components/chat/ComposerTaskAdvisor.vue');
const taskCapabilityActionsPath = join(process.cwd(), 'src/data/task-capability-actions.ts');
const composerPath = join(process.cwd(), 'src/components/chat/Composer.vue');
const chatPath = join(process.cwd(), 'src/views/chat/index.vue');
const goalsPath = join(process.cwd(), 'src/views/goals/index.vue');
const roomPath = join(process.cwd(), 'src/views/chat-room/index.vue');
const taskDraftPath = join(process.cwd(), 'src/composables/useTaskDraft.ts');
const enPath = join(process.cwd(), 'src/locales/en-US.ts');
const zhPath = join(process.cwd(), 'src/locales/zh-CN.ts');

describe('composer task actions UX', () => {
  it('moves advanced capabilities into the active chat task flow', () => {
    const taskActions = readFileSync(taskActionsPath, 'utf8');
    const taskAdvisor = readFileSync(taskAdvisorPath, 'utf8');
    const taskCapabilityActions = readFileSync(taskCapabilityActionsPath, 'utf8');
    const composer = readFileSync(composerPath, 'utf8');
    const chat = readFileSync(chatPath, 'utf8');
    const goals = readFileSync(goalsPath, 'utf8');
    const room = readFileSync(roomPath, 'utf8');
    const taskDraft = readFileSync(taskDraftPath, 'utf8');
    const en = readFileSync(enPath, 'utf8');
    const zh = readFileSync(zhPath, 'utf8');

    expect(taskCapabilityActions).toContain("export type ComposerTaskAction =");
    for (const action of ['goal', 'cron', 'room', 'tools', 'model', 'memory', 'cost', 'lessons', 'sandbox', 'audit', 'proactive', 'intent']) {
      expect(taskCapabilityActions).toContain(`| '${action}'`);
      expect(taskCapabilityActions).toContain(`key: '${action}'`);
      expect(zh).toContain(`${action}:`);
      expect(en).toContain(`${action}:`);
    }
    expect(taskCapabilityActions).toContain("export const composerTaskActionGroups");
    expect(taskCapabilityActions).toContain("behavior: 'inline'");
    expect(taskCapabilityActions).toContain("behavior: 'pending'");
    expect(taskCapabilityActions).toContain("behavior: 'route'");
    expect(taskCapabilityActions).toContain('isInlineComposerTaskAction');
    expect(taskActions).toContain('composerTaskActionGroups');
    expect(taskActions).toContain('groupedActions');
    expect(taskActions).toContain('chat.composer.taskActions.groups.${section.group}');
    expect(taskActions).toContain('chat.composer.taskActions.prompts.${action}');
    expect(taskAdvisor).toContain('ComposerTaskActionPayload');
    expect(taskAdvisor).toContain('composerTaskActions');
    expect(taskAdvisor).toContain('action.keywords.test(text)');
    expect(taskAdvisor).toContain('task-advisor');
    expect(taskActions).toContain('chat.composer.taskActions.${action.key}.title');
    expect(taskActions).toContain('chat.composer.taskActions.${action.key}.desc');
    expect(composer).toContain('ComposerTaskActions');
    expect(composer).toContain('ComposerTaskAdvisor');
    expect(composer).toContain('isInlineComposerTaskAction(payload.action)');
    expect(composer).toContain("emit('taskAction', payload)");
    expect(chat).toContain("import { useTaskDraft }");
    expect(chat).toContain("openPendingTask('goal', payload.prompt)");
    expect(chat).toContain("openPendingTask('cron', payload.prompt)");
    expect(chat).toContain("openPendingTask('room', payload.prompt)");
    expect(taskDraft).toContain("export const GOAL_OBJECTIVE_KEY = 'panel.pendingGoalObjective'");
    expect(taskDraft).toContain("export const CRON_PROMPT_KEY = 'panel.pendingCronPrompt'");
    expect(taskDraft).toContain("export const ROOM_PROMPT_KEY = 'panel.pendingRoomPrompt'");
    expect(chat).toContain("payload.action === 'model'");
    expect(chat).toContain("hash: '#providers'");
    expect(goals).toContain('applyPendingGoalObjective');
    expect(goals).toContain("sessionStorage.getItem('panel.pendingGoalObjective')");
    expect(room).toContain('initializeRoomFromPendingPrompt');
    expect(room).toContain("sessionStorage.getItem('panel.pendingRoomPrompt')");
    expect(room.indexOf('input.value = pending')).toBeLessThan(room.indexOf('await store.fetchRooms()'));
    expect(room).toContain('catch (err)');
    expect(room).toContain('create-modal-draft');
    expect(room).toContain("t('chatRoom.pendingDraftLabel')");

    expect(zh).toContain('这次任务要怎么做');
    expect(zh).toContain('设为长线目标');
    expect(zh).toContain('安排定时执行');
    expect(zh).toContain('交给角色群聊');
    expect(zh).toContain('使用工具与 MCP');
    expect(zh).toContain('配置免费或本地模型');
    expect(zh).toContain('先控制成本');
    expect(zh).toContain('带上长期记忆');
    expect(zh).toContain('参考经验库');
    expect(zh).toContain('按沙箱任务处理');
    expect(zh).toContain('先做审计检查');
    expect(zh).toContain('主动发现风险');
    expect(zh).toContain('判断我该怎么用');
    expect(zh).toContain('建议下一步');
    expect(zh).toContain('待发送任务');
    expect(en).toContain('How should Hermes handle this?');
    expect(en).toContain('Set as long-running goal');
    expect(en).toContain('Schedule recurring run');
    expect(en).toContain('Send to role room');
    expect(en).toContain('Configure a free or local model');
    expect(en).toContain('Use tools and MCP');
    expect(en).toContain('Control cost first');
    expect(en).toContain('Include long-term memory');
    expect(en).toContain('Reference saved lessons');
    expect(en).toContain('Treat as sandboxed work');
    expect(en).toContain('Audit before continuing');
    expect(en).toContain('Find risks proactively');
    expect(en).toContain('Tell me what to use');
    expect(en).toContain('Suggested next step');
    expect(en).toContain('Task ready to send');
  });
});
