import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

const dashboardPath = join(process.cwd(), 'src/views/dashboard/index.vue');
const quickStartPath = join(process.cwd(), 'src/components/dashboard/DashboardQuickStart.vue');
const workbenchHubPath = join(process.cwd(), 'src/components/dashboard/DashboardWorkbenchHub.vue');
const taskLauncherPath = join(process.cwd(), 'src/components/dashboard/DashboardTaskLauncher.vue');
const firstRunPath = join(process.cwd(), 'src/components/dashboard/DashboardFirstRunPath.vue');
const enPath = join(process.cwd(), 'src/locales/en-US.ts');
const zhPath = join(process.cwd(), 'src/locales/zh-CN.ts');

describe('Dashboard quick start UX', () => {
  it('puts task-oriented next actions at the top of the dashboard', () => {
    const dashboard = readFileSync(dashboardPath, 'utf8');
    const quickStart = readFileSync(quickStartPath, 'utf8');
    const workbench = readFileSync(workbenchHubPath, 'utf8');
    const taskLauncher = readFileSync(taskLauncherPath, 'utf8');
    const firstRun = readFileSync(firstRunPath, 'utf8');
    const en = readFileSync(enPath, 'utf8');
    const zh = readFileSync(zhPath, 'utf8');

    expect(dashboard).toContain('DashboardWorkbenchHub');
    expect(dashboard).toContain('DashboardQuickStart');
    expect(dashboard).toContain('showSetupPath');
    expect(dashboard).toContain('v-if="showSetupPath"');
    expect(dashboard.indexOf('<DashboardWorkbenchHub')).toBeLessThan(dashboard.indexOf('<StatCard'));
    expect(workbench).toContain('DashboardTaskLauncher');
    expect(dashboard).toContain("dashboard.sections.operations.title");
    expect(dashboard).toContain("dashboard.sections.capabilities.title");
    expect(dashboard).toContain("dashboard.sections.history.title");
    expect(dashboard.indexOf('<CapabilityMap')).toBeGreaterThan(dashboard.indexOf('<OrchestrationCompareCard'));
    expect(workbench).toContain("route: '/chat'");
    expect(workbench).toContain("route: '/settings#providers'");
    expect(workbench).toContain("route: '/goals'");
    expect(workbench).toContain("route: '/chat-room'");
    expect(workbench).toContain("route: '/cron'");
    expect(workbench).toContain("route: '/developer#cli-parity'");
    expect(workbench).toContain("localStorage.setItem('panel.chat.draft.new'");
    expect(workbench).toContain("draftKey: 'dashboard.workbench.actions.chat.prompt'");
    expect(workbench).toContain("draftKey: 'dashboard.workbench.modes.direct.prompt'");
    expect(taskLauncher).toContain("localStorage.setItem('panel.chat.draft.new'");
    expect(taskLauncher).toContain("router.push({ path: '/chat'");
    expect(taskLauncher).toContain("router.push('/chat-room')");
    expect(taskLauncher).toContain("dashboard.workbench.launcher.examples");
    expect(taskLauncher).toContain('function onInputKeydown');
    expect(taskLauncher).toContain('@keydown="onInputKeydown"');
    expect(quickStart).toContain("route: '/settings#providers'");
    expect(quickStart).toContain("route: '/chat'");
    expect(quickStart).toContain("route: '/chat-room'");
    expect(quickStart).toContain("route: '/channels'");
    expect(quickStart).toContain("'/settings#system-health'");
    expect(quickStart).toContain("'/developer#doctor'");
    expect(quickStart).toContain('firstRunActions');
    expect(quickStart).toContain("key: 'freeLocal'");
    expect(quickStart).toContain("draftKey: 'dashboard.quickStart.firstRun.freeLocal.prompt'");
    expect(quickStart).toContain("localStorage.setItem('panel.chat.draft.new'");
    expect(quickStart).toContain('DashboardFirstRunPath');
    expect(firstRun).toContain('first-run-path');
    expect(firstRun).toContain('select: [action: FirstRunAction]');
    expect(quickStart).toContain('summaryKey');
    expect(en).toContain('AI command center');
    expect(en).toContain('Start with the AI task');
    expect(en).toContain('Run insights');
    expect(en).toContain('Choose the right Hermes surface');
    expect(en).toContain('Resume where you left off');
    expect(en).toContain('Configure free/local model');
    expect(en).toContain('Tell Hermes what to do first');
    expect(en).toContain('Start chat');
    expect(en).toContain('Official CLI parity');
    expect(en).toContain('Fastest path to the first reply');
    expect(en).toContain('Try free local');
    expect(en).toContain('Configure cloud model');
    expect(en).toContain('Choose conversation');
    expect(en).toContain('Choose the next action');
    expect(zh).toContain('AI 指令中心');
    expect(zh).toContain('先开始 AI 任务');
    expect(zh).toContain('运行洞察');
    expect(zh).toContain('选择合适的 Hermes 使用面');
    expect(zh).toContain('从上次停下的位置继续');
    expect(zh).toContain('配置免费/本地模型');
    expect(zh).toContain('先告诉 Hermes 要做什么');
    expect(zh).toContain('开始对话');
    expect(zh).toContain('官方 CLI 覆盖');
    expect(zh).toContain('最快获得第一条回复');
    expect(zh).toContain('试用免费本地');
    expect(zh).toContain('配置云端模型');
    expect(zh).toContain('选择对话方式');
    expect(zh).toContain('选择下一步操作');
  });
});
