import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

const bridgePath = join(process.cwd(), 'src/components/shared/FeatureTaskBridge.vue');
const toolsPath = join(process.cwd(), 'src/views/tools/index.vue');
const memoryPath = join(process.cwd(), 'src/views/memory/index.vue');
const costPath = join(process.cwd(), 'src/views/cost/index.vue');
const goalsPath = join(process.cwd(), 'src/views/goals/index.vue');
const roomPath = join(process.cwd(), 'src/views/chat-room/index.vue');
const developerPath = join(process.cwd(), 'src/views/developer/index.vue');
const channelsPath = join(process.cwd(), 'src/views/channels/index.vue');
const lessonsPath = join(process.cwd(), 'src/views/lessons/index.vue');
const sandboxPath = join(process.cwd(), 'src/views/sandbox/index.vue');
const auditPath = join(process.cwd(), 'src/views/audit/index.vue');
const proactivePath = join(process.cwd(), 'src/views/proactive/index.vue');
const intentPath = join(process.cwd(), 'src/views/intent/index.vue');
const enPath = join(process.cwd(), 'src/locales/en-US.ts');
const zhPath = join(process.cwd(), 'src/locales/zh-CN.ts');

describe('feature task bridge UX', () => {
  it('lets confusing feature pages feed a concrete task back into Chat', () => {
    const bridge = readFileSync(bridgePath, 'utf8');
    const tools = readFileSync(toolsPath, 'utf8');
    const memory = readFileSync(memoryPath, 'utf8');
    const cost = readFileSync(costPath, 'utf8');
    const goals = readFileSync(goalsPath, 'utf8');
    const room = readFileSync(roomPath, 'utf8');
    const developer = readFileSync(developerPath, 'utf8');
    const channels = readFileSync(channelsPath, 'utf8');
    const lessons = readFileSync(lessonsPath, 'utf8');
    const sandbox = readFileSync(sandboxPath, 'utf8');
    const audit = readFileSync(auditPath, 'utf8');
    const proactive = readFileSync(proactivePath, 'utf8');
    const intent = readFileSync(intentPath, 'utf8');
    const en = readFileSync(enPath, 'utf8');
    const zh = readFileSync(zhPath, 'utf8');

    expect(bridge).toContain("import { useTaskDraft }");
    expect(bridge).toContain('openChatDraft(props.prompt)');
    expect(bridge).toContain('openRoute(props.secondaryTo)');
    expect(bridge).toContain('ControlCenterIcon');
    expect(bridge).toContain('bridge-command');
    expect(bridge).toContain('bridge-action is-primary');

    expect(tools).toContain('FeatureTaskBridge');
    expect(tools).toContain('icon="tools"');
    expect(tools).toContain("command=\"hermes tools list\"");
    expect(tools).toContain("secondary-to=\"/developer#cli-parity\"");
    expect(memory).toContain('FeatureTaskBridge');
    expect(memory).toContain('icon="memory"');
    expect(memory).toContain("command=\"hermes memory\"");
    expect(memory).toContain("secondary-to=\"/tools\"");
    expect(cost).toContain('FeatureTaskBridge');
    expect(cost).toContain('icon="cost"');
    expect(cost).toContain('ErrorBanner');
    expect(cost).toContain("command=\"hermes insights\"");
    expect(cost).toContain("secondary-to=\"/settings#providers\"");
    expect(cost).toContain('const error = ref<string | null>(null)');
    expect(cost).toContain('@retry="loadCostOverview"');
    expect(goals).toContain('FeatureTaskBridge');
    expect(goals).toContain('icon="goals"');
    expect(goals).toContain("secondary-to=\"/chat-room\"");
    expect(room).toContain('FeatureTaskBridge');
    expect(room).toContain('icon="chatRoom"');
    expect(room).toContain('room-task-bridge');
    expect(developer).toContain('FeatureTaskBridge');
    expect(developer).toContain('icon="developer"');
    expect(developer).toContain('command="hermes doctor"');
    expect(channels).toContain('FeatureTaskBridge');
    expect(channels).toContain('icon="channels"');
    expect(channels).toContain('command="hermes pairing list"');
    expect(channels).toContain('v-else-if="store.error"');
    expect(lessons).toContain('FeatureTaskBridge');
    expect(lessons).toContain('icon="lessons"');
    expect(lessons).toContain('v-else-if="error"');
    expect(sandbox).toContain('FeatureTaskBridge');
    expect(sandbox).toContain('icon="sandbox"');
    expect(sandbox).toContain('function checkSandboxAvailability');
    expect(audit).toContain('FeatureTaskBridge');
    expect(audit).toContain('icon="audit"');
    expect(audit).toContain('v-else-if="error"');
    expect(proactive).toContain('FeatureTaskBridge');
    expect(proactive).toContain('icon="proactive"');
    expect(proactive).toContain('v-else-if="error"');
    expect(intent).toContain('FeatureTaskBridge');
    expect(intent).toContain('icon="intent"');
    expect(intent).toContain('retryLastError');

    expect(en).toContain('Use tools in Chat');
    expect(en).toContain('Use memory in Chat');
    expect(en).toContain('Plan with cost in Chat');
    expect(en).toContain('Plan goal in Chat');
    expect(en).toContain('Plan role room in Chat');
    expect(en).toContain('Plan diagnostics in Chat');
    expect(en).toContain('Plan channel workflow');
    expect(en).toContain('Use lessons in Chat');
    expect(en).toContain('Plan sandbox run');
    expect(en).toContain('Review audit in Chat');
    expect(en).toContain('Prioritize in Chat');
    expect(en).toContain('Plan intent route');
    expect(zh).toContain('在 Chat 使用工具');
    expect(zh).toContain('在 Chat 使用记忆');
    expect(zh).toContain('在 Chat 做成本规划');
    expect(zh).toContain('在 Chat 规划目标');
    expect(zh).toContain('在 Chat 规划群聊');
    expect(zh).toContain('在 Chat 规划诊断');
    expect(zh).toContain('规划渠道工作流');
    expect(zh).toContain('在 Chat 使用经验');
    expect(zh).toContain('规划 Sandbox 执行');
    expect(zh).toContain('在 Chat 审查审计');
    expect(zh).toContain('在 Chat 排优先级');
    expect(zh).toContain('规划意图路由');
  });
});
